frames = [
    # compiled by XD
    [['early'], ['late']],
    [['anterior'], ['posterior']],
    [['dynamic'], ['static']],
    [['mortal'], ['immortal']],
    [['occupied'], ['vacant']],
    [['intelligent', 'wise', 'smart'], ['stupid']],
    [['arrogant'], ['modest', 'timid']],
    [['benevolent'], ['vicious']],
    [['educated', 'knowledgeable'], ['ignorant']],
    [['honest'], ['dishonest']],
    [['healthy'], ['unhealthy']],
    [['correct'], ['incorrect']],
    [['confident'], ['uncertain']],
    # from BATS
    [['abundant'], ['tight', 'insufficient']],
    [['beautiful'], ['grotesque', 'monstrous']],
    [['big', 'large'], ['small']],
    [['wide'], ['narrow']],
    [['short'], ['tall', 'long']],
    [['heavy'], ['light']],
    [['bright'], ['dark']],
    [['hard'], ['soft']],
    [['hot', 'warm'], ['cold', 'cool']],
    [['slow'], ['fast', 'quick']],
    [['cheap', 'inexpensive'], ['expensive', 'dear']],
    [['clear'], ['unclear', 'undefined']],
    [['near', 'close'], ['far', 'distant']],
    [['colorful'], ['neutral', 'faded']],
    [['common', 'ordinary'], ['uncommon', 'extraordinary']],
    [['competent'], ['incompetent', 'inefficient']],
    [['concerned'], ['casual', 'detached']],
    [['artificial', 'unnatural'], ['natural']],
    [['dangerous'], ['safe', 'harmless']],
    [['decisive'], ['hesitant']],
    [['energetic'], ['inactive']],
    [['familiar'], ['unfamiliar', 'strange']],
    [['happy'], ['unhappy', 'melancholy']],
    [['interesting'], ['boring']],
    [['normal'], ['abnormal', 'irregular']],
    [['rich'], ['poor']],
    [['formal'], ['liberal', 'informal']],
    [['willing', 'voluntary'], ['unwilling', 'involuntary']],
    [['young'], ['old', 'aged']],
    [['easy', 'simple'], ['difficult', 'hard']], #, 'challenging', 'uneasy']],
    # from WNLaMPro
    [['new'], ['old']],
    [['many'], ['few', 'little']],
    [['high'], ['low']],
    [['general'], ['specific']],
    [['international'], ['national']],
    [['local'], ['national']],
    [['popular'], ['unpopular']],
    [['northern'], ['southern']],
    # [['married'], ['unmarried']],
    [['good'], ['bad']],
    [['available'], ['unavailable']],
    [['successful'], ['unsuccessful']],
    [['strong'], ['weak']],
    [['limited'], ['unlimited']],
    [['foreign'], ['domestic']],
    [['related'], ['unrelated']],
    [['legal'], ['illegal']],
    [['likely'], ['unlikely']],
    [['rural'], ['urban']],
    [['potential'], ['actual']],
    [['necessary'], ['unnecessary']],
    [['positive'], ['negative']],
    [['internal'], ['external']],
    [['effective'], ['ineffective']],
    [['affected'], ['unaffected']],
    [['experienced'], ['inexperienced']],
    [['instrumental'], ['vocal']],
    [['civilian'], ['military']],
    [['conventional'], ['unconventional']],
    [['usual'], ['unusual']],
    [['endemic'], ['epidemic']],
    [['vertical'], ['inclined']],
    [['automatic'], ['manual']],
    [['accessible'], ['inaccessible']],
    [['emotional'], ['cerebral']],
    [['theoretical'], ['empirical']],
    [['eligible'], ['ineligible']],
    [['valid'], ['invalid']],
    [['sudden'], ['gradual']],
    [['reasonable'], ['unreasonable']],
    [['compatible'], ['incompatible']],
    [['acceptable'], ['unacceptable']],
    [['comfortable'], ['uncomfortable']],
    [['rational'], ['irrational']],
    [['unconscious'], ['conscious']],
    # [['homosexual'], ['heterosexual']],
    [['induced'], ['spontaneous']],
    [['peripheral'], ['central']],
    [['unconstitutional'], ['constitutional']],
    [['lawful'], ['unlawful']],
    [['undesirable'], ['desirable']],
    [['unpredictable'], ['predictable']],
    [['impractical'], ['practical']],
    # [['unequal'], ['equal']],
    [['immoral'], ['moral']],
    [['unconditional'], ['conditional']],
    [['unfavorable'], ['favorable']],
    [['unrealistic'], ['realistic']],
    [['impartial'], ['partial']],
    [['irresponsible'], ['responsible']],
    [['unprepared'], ['prepared']],
    [['insensitive'], ['sensitive']],
    [['unethical'], ['ethical']],
    [['frivolous'], ['serious']],
    [['pessimistic'], ['optimistic']],
    [['believable'], ['incredible']]
]

person_adjs = [
    [['tall'], ['short']],
    [['insensitive'], ['sensitive']],
    [['silent'], ['loud']],
    [['wrong'], ['right']],
    [['uninteresting'], ['interesting']],
    [['sleepy'], ['awake']],
    [['sad'], ['happy']],
    [['fat'], ['thin']],
    [['conscious'], ['unconscious']],
    [['careless'], ['careful']],
    [['shy'], ['outgoing']],
    [['diligent'], ['lazy']],
    [['polite'], ['rude']],
    [['quick'], ['slow']],
    [['stupid'], ['clever']],
    [['ignorant'], ['knowledgeable']],
    [['uncomfortable'], ['comfortable']],
    [['cerebral'], ['emotional']],
    [['serious'], ['frivolous']],
    [['pessimistic'], ['optimistic']],
    [['honest'], ['dishonest']],
    [['healthy'], ['unhealthy']],
    [['energetic'], ['inactive']],
    [['hesitant'], ['decisive']],
    [['dangerous'], ['harmless']],
    [['ugly'], ['beautiful']],
    [['selfish'], ['selfless']],
    [['rich'], ['poor']],
    [['light'], ['heavy']],
    [['big'], ['small']],
    [['sane'], ['mad']],
    [['young'], ['old']],
    [['brave'], ['cowardly']],
    [['unpopular'], ['popular']],
    [['strong'], ['weak']],
    [['passive'], ['aggressive']],
    [['impatient'], ['patient']],
    [['arrogant'], ['humble']],
    [['responsible'], ['irresponsible']],
    [['determined'], ['indecisive']],
    [['irrational'], ['rational']],
    [['insecure'], ['confident']],
    [['single'], ['married']],
    [['kind'], ['cruel']],
    [['messy'], ['tidy']]
]
